apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-obvbfvfr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-obvbfvfr 
  name: python-obvbfvfr
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-obvbfvfr
    weight: 100 
